class ValidationErrors < ActiveRecord::Base
  def self.track: (untyped invalid_model) -> untyped

  module Trackable
    def self.included: (untyped base) -> untyped

    # :nodoc:
    module ClassMethods
      def track_validation_errors: () -> untyped
    end

    module InstanceMethods
      def save: (**untyped options) -> untyped

      # Attempts to save the record just like {ActiveRecord::Base#save}[rdoc-ref:Base#save] but
      # will raise an ActiveRecord::RecordInvalid exception instead of returning +false+ if the record is not valid.
      def save!: (**untyped options) -> untyped
    end
  end
end
